name: Despliegue Produccion (TF Cloud)

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.0
        # Esto configura el token autom치ticamente para el setup, 
        # pero es mejor ser explicito en los pasos siguientes.
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init
      env:
        # Token para hablar con la nube de HashiCorp (Memoria)
        TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
        # Credenciales para hablar con AWS (Infraestructura)
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1

    - name: Terraform Apply
      # Pasamos el hash del commit para que detecte cambios en el c칩digo
      run: terraform apply -auto-approve -var="commit_hash=${{ github.sha }}"
      env:
        TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1

    - name: Instance Refresh (Force Update)
      run: |
        # 1. Intentamos cancelar cualquier refresh anterior que se haya quedado colgado
        # El "|| true" hace que si no hay nada que cancelar, no de error.
        aws autoscaling cancel-instance-refresh --auto-scaling-group-name asg-final-pro || true
        
        # 2. Esperamos unos segundos para que AWS procese la cancelaci칩n
        echo "Esperando limpieza de procesos anteriores..."
        sleep 10
        
        # 3. Iniciamos el nuevo refresh con tu c칩digo nuevo
        aws autoscaling start-instance-refresh \
          --auto-scaling-group-name asg-final-pro \
          --preferences '{"MinHealthyPercentage": 50, "InstanceWarmup": 120}'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1